# Generated by Django 5.2.4 on 2025-09-05 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_excel', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('row_total', models.FloatField(default=0.0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='custos.uploadedfile')),
            ],
            options={
                'verbose_name': 'Dados de Despesa',
                'verbose_name_plural': 'Dados de Despesas',
            },
        ),
    ]
