# Generated by Django 5.2.4 on 2025-09-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Arquivo sem nome', max_length=255),
        ),
    ]
